common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *common
  database: recruiter_development
  username: jrhorn424

test:
  <<: *common
  database: recruiter_test

# Heroku overwrites this file when starting the app, so this isn't strictly
# necessary, but included here for completeness.
production:
  <<: *common
  database: recruiter
  username: deploy
